import { Group, Progress, Text } from '@mantine/core';
import { Dropzone, FileRejection } from '@mantine/dropzone';
import { IconUpload } from '@tabler/icons-react';
import { ReactNode, useCallback, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ErrorAlert } from '../../components/ErrorAlert.tsx';
import { useAsync } from '../../hooks/use-async.ts';
import { useLogParser } from '../../hooks/useLogParser.ts';
import { StrategySession } from '../../models.ts';
import { useStore } from '../../store.ts';
import { calculateMaxDrawdown, calculateSharpeRatio } from '../../utils/quantEngine.ts';
import { HomeCard } from './HomeCard.tsx';

function DropzoneContent(): ReactNode {
  return (
    <Group justify="center" gap="xl" style={{ minHeight: 80, pointerEvents: 'none' }}>
      <IconUpload size={40}></IconUpload>
      <Text size="xl" inline={true}>
        Drag file here or click to select file
      </Text>
    </Group>
  );
}

export function LoadFromFile(): ReactNode {
  const navigate = useNavigate();

  const [error, setError] = useState<Error>();

  const setAlgorithm = useStore(state => state.setAlgorithm);
  const setLoadedLogFilename = useStore(state => state.setLoadedLogFilename);
  const addStrategySession = useStore(state => state.addStrategySession);
  const logParser = useLogParser();

  const onDrop = useAsync(async (files: File[]) => {
    setError(undefined);

    let latestName: string | null = null;
    let latestAlgorithm: StrategySession['algorithm'] | null = null;

    for (let i = 0; i < files.length; i += 1) {
      const file = files[i];
      const rawLogs = await file.text();
      const algorithm = await logParser.parseFromText(rawLogs);
      const pnlHistory = algorithm.activityLogs.map(row => row.profitLoss);
      const tradeCount = algorithm.data.reduce((acc, row) => {
        let rowTrades = 0;
        for (const symbol of Object.keys(row.state.ownTrades)) {
          rowTrades += row.state.ownTrades[symbol].length;
        }
        return acc + rowTrades;
      }, 0);

      const totalPnl = pnlHistory.length > 0 ? pnlHistory[pnlHistory.length - 1] : 0;
      const session: StrategySession = {
        id: `${Date.now()}-${i}-${Math.random().toString(36).slice(2, 8)}`,
        name: file.name,
        timestamp: new Date().toISOString(),
        rawLogs,
        computedMetrics: {
          totalPnl,
          sharpeRatio: calculateSharpeRatio(pnlHistory),
          maxDrawdown: calculateMaxDrawdown(pnlHistory),
          tradeCount,
        },
        algorithm,
      };

      addStrategySession(session);
      latestName = file.name;
      latestAlgorithm = algorithm;
    }

    if (latestAlgorithm !== null) {
      setAlgorithm(latestAlgorithm);
      setLoadedLogFilename(latestName);
      navigate('/visualizer');
    }
  });

  const onReject = useCallback((rejections: FileRejection[]) => {
    const messages: string[] = [];

    for (const rejection of rejections) {
      const errorType = {
        'file-invalid-type': 'Invalid type, only log files are supported.',
        'file-too-large': 'File too large.',
        'file-too-small': 'File too small.',
        'too-many-files': 'Too many files.',
      }[rejection.errors[0].code]!;

      messages.push(`Could not load algorithm from ${rejection.file.name}: ${errorType}`);
    }

    setError(new Error(messages.join('<br/>')));
  }, []);

  return (
    <HomeCard title="Load from file">
      <Text>
        Supports log files that are in the same format as the ones generated by the Prosperity servers. This format is
        undocumented, but you can get an idea of what it looks like by downloading a log file from a submitted
        algorithm.
      </Text>

      {error && <ErrorAlert error={error} />}
      {onDrop.error && <ErrorAlert error={onDrop.error} />}
      {logParser.loading && (
        <>
          <Text size="sm" c="marmot-text">
            Processing log... {logParser.loadingStage}
          </Text>
          <Progress value={logParser.loadingProgress} color="#FF8C00" mt="xs" mb="sm" />
        </>
      )}

      <Dropzone onDrop={onDrop.call} onReject={onReject} multiple={true} loading={onDrop.loading || logParser.loading}>
        <Dropzone.Idle>
          <DropzoneContent />
        </Dropzone.Idle>
        <Dropzone.Accept>
          <DropzoneContent />
        </Dropzone.Accept>
      </Dropzone>
    </HomeCard>
  );
}
