import { Button, Code, Progress, Text, TextInput } from '@mantine/core';
import axios from 'axios';
import { FormEvent, ReactNode, useCallback, useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ErrorAlert } from '../../components/ErrorAlert.tsx';
import { useAsync } from '../../hooks/use-async.ts';
import { useLogParser } from '../../hooks/useLogParser.ts';
import { StrategySession } from '../../models.ts';
import { useStore } from '../../store.ts';
import { calculateMaxDrawdown, calculateSharpeRatio } from '../../utils/quantEngine.ts';
import { HomeCard } from './HomeCard.tsx';

export function LoadFromUrl(): ReactNode {
  const [url, setUrl] = useState('');

  const algorithm = useStore(state => state.algorithm);
  const setAlgorithm = useStore(state => state.setAlgorithm);
  const setLoadedLogFilename = useStore(state => state.setLoadedLogFilename);
  const addStrategySession = useStore(state => state.addStrategySession);
  const logParser = useLogParser();

  const navigate = useNavigate();
  const searchParams = useSearchParams()[0];

  const loadAlgorithm = useAsync(async (logsUrl: string): Promise<void> => {
    const logsResponse = await axios.get<string>(logsUrl, { responseType: 'text' });
    const parsedAlgorithm = await logParser.parseFromText(logsResponse.data);
    setAlgorithm(parsedAlgorithm);
    try {
      const parsed = new URL(logsUrl);
      const candidate = parsed.pathname.split('/').filter(Boolean).pop() ?? '';
      setLoadedLogFilename(candidate.length > 0 ? candidate : parsed.host);
    } catch {
      setLoadedLogFilename(logsUrl);
    }
    const pnlHistory = parsedAlgorithm.activityLogs.map(row => row.profitLoss);
    const tradeCount = parsedAlgorithm.data.reduce((acc, row) => {
      let rowTrades = 0;
      for (const symbol of Object.keys(row.state.ownTrades)) {
        rowTrades += row.state.ownTrades[symbol].length;
      }
      return acc + rowTrades;
    }, 0);
    const sessionName = (() => {
      try {
        const parsed = new URL(logsUrl);
        return parsed.pathname.split('/').filter(Boolean).pop() || parsed.host;
      } catch {
        return logsUrl;
      }
    })();
    const session: StrategySession = {
      id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      name: sessionName,
      timestamp: new Date().toISOString(),
      rawLogs: logsResponse.data,
      computedMetrics: {
        totalPnl: pnlHistory.length > 0 ? pnlHistory[pnlHistory.length - 1] : 0,
        sharpeRatio: calculateSharpeRatio(pnlHistory),
        maxDrawdown: calculateMaxDrawdown(pnlHistory),
        tradeCount,
      },
      algorithm: parsedAlgorithm,
    };
    addStrategySession(session);
    navigate(`/visualizer?open=${logsUrl}`);
  });

  const onSubmit = useCallback(
    (event?: FormEvent<HTMLFormElement>) => {
      event?.preventDefault();

      if (url.trim().length > 0) {
        loadAlgorithm.call(url);
      }
    },
    [loadAlgorithm],
  );

  useEffect(() => {
    if (algorithm !== null || loadAlgorithm.loading) {
      return;
    }

    if (!searchParams.has('open')) {
      return;
    }

    const url = searchParams.get('open') || '';

    setUrl(url);

    if (url.trim().length > 0) {
      loadAlgorithm.call(url);
    }
  }, []);

  const currentUrl = window.location.origin + window.location.pathname;

  return (
    <HomeCard title="Load from URL">
      <Text>
        Supports URLs to log files that are in the same format as the ones generated by the Prosperity servers. This
        format is undocumented, but you can get an idea of what it looks like by downloading a log file from a submitted
        algorithm. The URL must allow cross-origin requests from the visualizer&apos;s website.
      </Text>
      <Text>
        This input type can also be used by browsing to <Code>{currentUrl}?open=&lt;url&gt;</Code>.
      </Text>

      {loadAlgorithm.error && <ErrorAlert error={loadAlgorithm.error} />}
      {logParser.loading && (
        <>
          <Text size="sm" c="marmot-text">
            Processing log... {logParser.loadingStage}
          </Text>
          <Progress value={logParser.loadingProgress} color="#FF8C00" mt="xs" mb="sm" />
        </>
      )}

      <form onSubmit={onSubmit}>
        <TextInput
          label="URL"
          placeholder="URL"
          value={url}
          onInput={e => setUrl((e.target as HTMLInputElement).value)}
        />

        <Button fullWidth type="submit" loading={loadAlgorithm.loading || logParser.loading} mt="sm">
          <div>Load</div>
        </Button>
      </form>
    </HomeCard>
  );
}
